### ISSUE TITLE
bytearray index out of range

### ISSUE THREAD

**Issue by bandnerd210** [adafruit/Adafruit_CircuitPython_DisplayIO_SSD1305#10]
Traceback (most recent call last):
  File "/home/pi/Documents/motorcycle Pi/example.py", line 27, in <module>
    display = adafruit_displayio_ssd1305.SSD1305(display_bus, width=WIDTH, height=HEIGHT)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_displayio_ssd1305.py", line 103, in __init__
    colstart=colstart,
  File "/home/pi/.local/lib/python3.7/site-packages/displayio/display.py", line 148, in __init__
    self._initialize(init_sequence)
  File "/home/pi/.local/lib/python3.7/site-packages/displayio/display.py", line 182, in _initialize
    data_size = init_sequence[i + 1]
IndexError: bytearray index out of range

i get this error when running the example code(s). Both the one in the homepage and the one as a file. I originally had to also install the blinka_displayio, display_text, and ssd1305 packages. I also believe i had to enable SPI with dtparam=spi=on. really not sure what else the problem could be. Thanks for the help.

**Comment by ladyada** [comment]
what is the exact hardware you're using the code with?

**Comment by bandnerd210** [comment]
> what is the exact hardware you're using the code with?

Raspberry pi zero v1.3 running Raspberry Pi OS with desktop (raspbian) V5.4 released December 2nd from the official website.

**Comment by ladyada** [comment]
the display you are using?

**Comment by bandnerd210** [comment]
2.23 inch OLED Display HAT for Raspberry Pi 2B/3B/4B/Zero/Zero W Jetson Nano 128×32 Pixels SPI/I2C Interface

This is an OLED display HAT for Raspberry Pi, 2.23inch diagonal, 128×32 pixels, with embedded SSD1305 driver, communicating via SPI or I2C interface

bought on Amazon... sorry! Looks similar to your Adafruit 2.23" Monochrome OLED Bonnet for Raspberry Pi but SPI instead of I2C. I am hoping for a fast refresh rate so that's why I went with SPI.

**Comment by ladyada** [comment]
yeah we dont own and haven't tested SSD1305 with SPI... so we dont know if it will work! please ask the vendor for tech support - they will have code you can use

**Comment by bandnerd210** [comment]
Ok. What's this code for then?

**Comment by makermelissa** [comment]
Monochrome/Grayscale OLED support hasn't been added to blinka displayio. Only Color OLEDs and TFTs so far.

**Comment by bandnerd210** [comment]
ok. thank you for the help!
