### ISSUE TITLE
Missing Type Annotations

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_DisplayIO_SSD1305#14]
There are missing type annotations for some functions in this library.

The `typing` module does not exist on CircuitPython devices so the import needs to be wrapped in try/except to catch the error for missing import. There is an example of how that is done here:

```python
try:
    from typing import List, Tuple
except ImportError:
    pass
```

Once imported the typing annotations for the argument type(s), and return type(s) can be added to the function signature. Here is an example of a function that has had this done already:

```python
def wrap_text_to_pixels(
    string: str, max_width: int, font=None, indent0: str = "", indent1: str = ""
) -> List[str]:
```
If you are new to Git or Github we have a guide about contributing to our projects here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

There is also a guide that covers our CI utilities and how to run them locally to ensure they will pass in Github Actions here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code In particular the pages: `Sharing docs on ReadTheDocs` and `Check your code with pre-commit` contain the tools to install and commands to run locally to run the checks.

If you are attempting to resolve this issue and need help, you can post a comment on this issue and tag both @foamyguy and @kattni or reach out to us on Discord: https://adafru.it/discord in the `#circuitpython-dev` channel.

The following locations are reported by mypy to be missing type annotations:

- [ ] adafruit_displayio_ssd1305.py:68

**Comment by tcfranks** [comment]
@FoamyGuy , @kattni , or @tekktrik 

The init on this part is def __init__(self, bus, **kwargs) -> None

bus can be spi or i2c: in the past I've used displayio.I2C or displayio.Fourwire , so does this really make any difference here?  or is there a better way to annotate 'bus'?

**Comment by FoamyGuy** [comment]
@tcfranks 

Looking into the code it looks like `bus` gets passed along to the displayio.Display() constructor which in the docs here: https://docs.circuitpython.org/en/latest/shared-bindings/displayio/index.html?highlight=displayio.Display is typed as `displayio._DisplayBus` so I think it could match that here, though I'm unsure if the leading underscore means we shouldn't actually use that for the typing information in the library. 

Another option, as you noted in the discord is using something like `Union[I2C, FourWire]` which I also think is good. Perhaps even better since it doesn't use anything "private" I would probably lean toward doing it this way to start and we can get input from others. 

Perhaps there should be something in `circuitpython_typing` for this ultimately as well.

**Comment by tekktrik** [comment]
We could probably even have it directly in the Blinka displayio library.  The only example I see is a FourWire, are there any I2C ones as well?

**Comment by tcfranks** [comment]
> 

it's in sampletest as well, just commented out.

# Use for SPI
spi = board.SPI()
oled_cs = board.D5
oled_dc = board.D6
display_bus = displayio.FourWire(
    spi, command=oled_dc, chip_select=oled_cs, baudrate=1000000, reset=oled_reset
)

# Use for **I2C**
# i2c = **board.I2C()**
**# display_bus = displayio.I2CDisplay(i2c, device_address=0x3c, reset=oled_reset)**

**Comment by tcfranks** [comment]
> We could probably even have it directly in the Blinka displayio library. The only example I see is a FourWire, are there any I2C ones as well?

it's in sampletest as well, just commented out:

# Use for SPI
spi = board.SPI()
oled_cs = board.D5
oled_dc = board.D6
display_bus = displayio.FourWire(
    spi, command=oled_dc, chip_select=oled_cs, baudrate=1000000, reset=oled_reset
)

_Use for I2C
i2c = board.I2C()
display_bus = displayio.I2CDisplay(i2c, device_address=0x3c, reset=oled_reset)_

**Comment by tcfranks** [comment]
sorry - had issues with the hash sign in comment
